#!/bin/bash

# MySQL client - needed by mariadb:console and mariadb:dump
# mysql-client is a metapackage
apt-get update
apt-get -y install mysql-client

# Build docker image
git clone https://github.com/Kloadut/dokku-md-dockerfiles /tmp/dokku-md-dockerfiles
docker build -q=true -t kloadut/mariadb /tmp/dokku-md-dockerfiles
rm -rf /tmp/dokku-md-dockerfiles
